name = "M8"
uuid = "060d7059-869b-42ee-b950-cd4f26bf01e8"
repo = "https://github.com/hustf/M8"
description = "Open access private Julia registry"

[packages]
5ee08b94-2369-4f4a-b8c7-99333ba35fb0 = { name = "Unitfu", path = "U/Unitfu" }
e6be9192-89dc-11e9-36e6-5dbcb28f419e = { name = "MechanicalUnits", path = "M/MechanicalUnits" }
