name = "M8"
uuid = "060d7059-869b-42ee-b950-cd4f26bf01e8"
repo = "https://github.com/hustf/M8"
description = "Open access private Julia registry"

[packages]
183f2c95-4b91-4df3-9bd2-197e8f9edb13 = { name = "MechanicalSketch", path = "M/MechanicalSketch" }
2532746b-52b5-4539-9431-8bb183ab067f = { name = "MechGlueDiffEqBase", path = "M/MechGlueDiffEqBase" }
3017d99d-ab52-4519-99a2-fa9ddc4637fe = { name = "MechGluecode", path = "M/MechGluecode" }
5ee08b94-2369-4f4a-b8c7-99333ba35fb0 = { name = "Unitfu", path = "U/Unitfu" }
83168081-0482-427f-a8e5-e3977330cfc7 = { name = "MechGlueModelingToolkit", path = "M/MechGlueModelingToolkit" }
e6be9192-89dc-11e9-36e6-5dbcb28f419e = { name = "MechanicalUnits", path = "M/MechanicalUnits" }
