name = "M8"
uuid = "060d7059-869b-42ee-b950-cd4f26bf01e8"
repo = "https://github.com/hustf/M8"
description = "Open access private Julia registry"

[packages]
03a24088-0a82-4850-846f-2cad5d056ae1 = { name = "MechGluePlots", path = "M/MechGluePlots" }
07025e9e-5a27-4179-b043-88080b1ee239 = { name = "RouteSlopeDistance", path = "R/RouteSlopeDistance" }
0a5bb257-8fa1-4030-bf16-d79c742dcb15 = { name = "Stadnamn", path = "S/Stadnamn" }
183f2c95-4b91-4df3-9bd2-197e8f9edb13 = { name = "MechanicalSketch", path = "M/MechanicalSketch" }
2532746b-52b5-4539-9431-8bb183ab067f = { name = "MechGlueDiffEqBase", path = "M/MechGlueDiffEqBase" }
3017d99d-ab52-4519-99a2-fa9ddc4637fe = { name = "MechGluecode", path = "M/MechGluecode" }
306ff6e8-cf68-49cb-8c42-e7ffdeba4da8 = { name = "ReplSpotifyPlayer", path = "R/ReplSpotifyPlayer" }
5ee08b94-2369-4f4a-b8c7-99333ba35fb0 = { name = "Unitfu", path = "U/Unitfu" }
6aa70590-773c-4af3-96e3-9e675ae1cb83 = { name = "MechGlueRecursiveArrayTools", path = "M/MechGlueRecursiveArrayTools" }
83168081-0482-427f-a8e5-e3977330cfc7 = { name = "MechGlueModelingToolkit", path = "M/MechGlueModelingToolkit" }
909dfbbc-cb73-418e-9556-eed3773b40ca = { name = "LuxorLayout", path = "L/LuxorLayout" }
a2cecc3b-2043-4d36-9615-d8139ca22695 = { name = "MechGlueInterpolations", path = "M/MechGlueInterpolations" }
b292befe-0c80-425c-929c-656b711f1b2a = { name = "StopsAndTimetables", path = "S/StopsAndTimetables" }
bc38f42f-d837-40aa-8305-15f3941c28e9 = { name = "LuxorLabels", path = "L/LuxorLabels" }
d7e0e77e-ebb7-4d52-98f7-0a2e09d5d09a = { name = "RouteMap", path = "R/RouteMap" }
dcf5437e-85d8-460a-98f8-69920db83c61 = { name = "BitmapMaps", path = "B/BitmapMaps" }
e6be9192-89dc-11e9-36e6-5dbcb28f419e = { name = "MechanicalUnits", path = "M/MechanicalUnits" }
efba8334-88fd-495a-b060-0ad2334728aa = { name = "LuxorMareyDiagram", path = "L/LuxorMareyDiagram" }
